SELECT nation, o_year, STRING_AGG(CONCAT('(',profit.prov  , ')', ' ⊗ ', amount), ' +sum ' ORDER BY nation) AS sum_profit, CONCAT('δ(',STRING_AGG(profit.prov  , ' + ' ORDER BY nation),')') AS prov FROM (SELECT nation.n_name AS nation, EXTRACT(year FROM orders.o_orderdate) AS o_year, lineitem.l_extendedprice * (1 - lineitem.l_discount) - partsupp.ps_supplycost * lineitem.l_quantity AS amount, part.prov || ' . ' || lineitem.prov || ' . ' || orders.prov || ' . ' || supplier.prov || ' . ' || partsupp.prov || ' . ' || nation.prov AS prov FROM part INNER JOIN lineitem ON part.p_partkey = lineitem.l_partkey INNER JOIN orders ON orders.o_orderkey = lineitem.l_orderkey INNER JOIN supplier ON supplier.s_suppkey = lineitem.l_suppkey INNER JOIN partsupp ON partsupp.ps_suppkey = lineitem.l_suppkey AND partsupp.ps_partkey = lineitem.l_partkey INNER JOIN nation ON supplier.s_nationkey = nation.n_nationkey WHERE part.p_name LIKE '%burlywood%') AS profit GROUP BY nation, o_year ORDER BY nation, o_year DESC

SELECT c_custkey, c_name, c_acctbal, n_name, c_address, c_phone, c_comment, STRING_AGG(CONCAT('(', customer.prov || ' . ' || orders.prov || ' . ' || lineitem.prov || ' . ' || nation.prov, ')', ' ⊗ ', l_extendedprice * (1 - l_discount)), ' +sum ' ORDER BY c_custkey) AS revenue, CONCAT('δ(', STRING_AGG(customer.prov || ' . ' || orders.prov || ' . ' || lineitem.prov || ' . ' || nation.prov, ' + ' ORDER BY c_custkey), ')') AS prov FROM customer INNER JOIN orders ON customer.c_custkey = orders.o_custkey INNER JOIN lineitem ON lineitem.l_orderkey = orders.o_orderkey INNER JOIN nation ON customer.c_nationkey = nation.n_nationkey WHERE orders.o_orderdate >= TO_DATE('1993-11-01', 'YYYY-MM-DD') AND orders.o_orderdate < TO_DATE('1994-02-01', 'YYYY-MM-DD') AND lineitem.l_returnflag = 'R' GROUP BY customer.c_custkey, customer.c_name, customer.c_acctbal, customer.c_phone, nation.n_name, customer.c_address, customer.c_comment ORDER BY revenue DESC LIMIT 20;

SELECT subHaving.ps_partkey, subHaving.value, subHaving.prov || ' . ' || C0.prov || ' . [' || subHaving.col12 || ' > ' || C0.col02 || ']' AS prov FROM (SELECT ps_partkey, STRING_AGG(CONCAT('(', partsupp.prov || ' . ' || supplier.prov || ' . ' || nation.prov, ')', ' ⊗ ', ps_supplycost * ps_availqty), ' +sum ' ORDER BY ps_partkey) AS value, STRING_AGG(CONCAT('(', partsupp.prov || ' . ' || supplier.prov || ' . ' || nation.prov, ')', ' ⊗ ', partsupp.ps_supplycost * partsupp.ps_availqty), ' +sum ' ORDER BY ps_partkey) AS col12, CONCAT('δ(', STRING_AGG(partsupp.prov || ' . ' || supplier.prov || ' . ' || nation.prov, ' + ' ORDER BY ps_partkey), ')') AS prov FROM partsupp INNER JOIN supplier ON partsupp.ps_suppkey = supplier.s_suppkey INNER JOIN nation ON supplier.s_nationkey = nation.n_nationkey WHERE nation.n_name = 'SAUDI ARABIA' GROUP BY partsupp.ps_partkey ORDER BY value DESC) AS subHaving, (SELECT STRING_AGG(CONCAT('(', partsupp.prov || ' . ' || supplier.prov || ' . ' || nation.prov, ')', ' ⊗ ', ps_supplycost * ps_availqty * 0.0010000000), ' +sum ') AS col02, CONCAT('δ(', STRING_AGG(partsupp.prov || ' . ' || supplier.prov || ' . ' || nation.prov, ' + '), ')') AS prov FROM partsupp INNER JOIN supplier ON partsupp.ps_suppkey = supplier.s_suppkey INNER JOIN nation ON supplier.s_nationkey = nation.n_nationkey WHERE nation.n_name = 'SAUDI ARABIA') C0

SELECT l_shipmode, STRING_AGG(CONCAT('(', orders.prov || ' . ' || lineitem.prov, ')', ' ⊗ ', CASE WHEN o_orderpriority = '1-URGENT' OR o_orderpriority = '2-HIGH' THEN 1 ELSE 0 END), ' +sum ' ORDER BY l_shipmode) AS high_line_count, STRING_AGG(CONCAT('(', orders.prov || ' . ' || lineitem.prov, ')', ' ⊗ ', CASE WHEN o_orderpriority <> '1-URGENT' AND o_orderpriority <> '2-HIGH' THEN 1 ELSE 0 END), ' +sum ' ORDER BY l_shipmode) AS low_line_count, CONCAT('δ(', STRING_AGG(orders.prov || ' . ' || lineitem.prov, ' + ' ORDER BY l_shipmode), ')') AS prov FROM orders INNER JOIN lineitem ON orders.o_orderkey = lineitem.l_orderkey WHERE lineitem.l_shipmode IN ('SHIP', 'MAIL') AND lineitem.l_commitdate < lineitem.l_receiptdate AND lineitem.l_shipdate < lineitem.l_commitdate AND lineitem.l_receiptdate >= TO_DATE('1996-01-01', 'YYYY-MM-DD') AND lineitem.l_receiptdate < TO_DATE('1997-01-01', 'YYYY-MM-DD') GROUP BY lineitem.l_shipmode ORDER BY lineitem.l_shipmode

SELECT STRING_AGG(CONCAT('(',lineitem.prov || ' . ' || part.prov, ')', ' ⊗ ', CASE WHEN p_type LIKE 'PROMO%' THEN l_extendedprice * (1 - l_discount) ELSE 0 END*100.00), ' +sum ') AS promo_revenue, STRING_AGG(CONCAT('(',lineitem.prov || ' . ' || part.prov, ')', ' ⊗ ', l_extendedprice * (1 - l_discount)), ' +sum ') AS promo_revenue, CONCAT('δ(',STRING_AGG(lineitem.prov || ' . ' || part.prov, ' + '),')') AS prov FROM lineitem INNER JOIN part ON lineitem.l_partkey = part.p_partkey WHERE lineitem.l_shipdate >= date '1996-10-01' AND lineitem.l_shipdate < date '1996-10-01' + INTERVAL '1' month

SELECT STRING_AGG(CONCAT('(', lineitem.prov || ' . ' || part.prov, ')', ' ⊗ ', lineitem.l_extendedprice * (1 - lineitem.l_discount)), ' +sum ') AS revenue, CONCAT('δ(', STRING_AGG(lineitem.prov || ' . ' || part.prov, ' + '), ')') AS prov FROM lineitem INNER JOIN part ON part.p_partkey = lineitem.l_partkey WHERE (part.p_brand = 'Brand#53' AND part.p_container IN ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG') AND lineitem.l_quantity >= 7 AND lineitem.l_quantity <= 7 + 10 AND part.p_size BETWEEN 1 AND 5 AND lineitem.l_shipmode IN ('AIR', 'AIR REG') AND lineitem.l_shipinstruct = 'DELIVER IN PERSON') OR (part.p_brand = 'Brand#53' AND part.p_container IN ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK') AND lineitem.l_quantity >= 17 AND lineitem.l_quantity <= 17 + 10 AND part.p_size BETWEEN 1 AND 10 AND lineitem.l_shipmode IN ('AIR', 'AIR REG') AND lineitem.l_shipinstruct = 'DELIVER IN PERSON') OR (part.p_brand = 'Brand#53' AND part.p_container IN ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG') AND lineitem.l_quantity >= 20 AND lineitem.l_quantity <= 20 + 10 AND part.p_size BETWEEN 1 AND 15 AND lineitem.l_shipmode IN ('AIR', 'AIR REG') AND lineitem.l_shipinstruct = 'DELIVER IN PERSON')

--
SELECT lineitem.l_orderkey, orders.o_orderdate, orders.o_shippriority, STRING_AGG(CONCAT('(', customer.prov || ' . ' || orders.prov || ' . ' || lineitem.prov, ')', ' ⊗ ', lineitem.l_extendedprice * (1 - lineitem.l_discount)), ' +sum ' ORDER BY lineitem.l_orderkey) AS revenue, CONCAT('δ(', STRING_AGG(customer.prov || ' . ' || orders.prov || ' . ' || lineitem.prov, ' + ' ORDER BY lineitem.l_orderkey), ')') AS prov FROM customer INNER JOIN orders ON customer.c_custkey = orders.o_custkey INNER JOIN lineitem ON lineitem.l_orderkey = orders.o_orderkey WHERE customer.c_mktsegment = 'FURNITURE' AND orders.o_orderdate < TO_DATE('1995-03-17', 'YYYY-MM-DD') AND lineitem.l_shipdate > TO_DATE('1995-03-17', 'YYYY-MM-DD') GROUP BY lineitem.l_orderkey, orders.o_orderdate, orders.o_shippriority ORDER BY orders.o_orderdate LIMIT 10;

SELECT nation.n_name, STRING_AGG(CONCAT('(', customer.prov || ' . ' || orders.prov || ' . ' || lineitem.prov || ' . ' || supplier.prov || ' . ' || nation.prov || ' . ' || region.prov, ')', ' ⊗ ', lineitem.l_extendedprice * (1 - lineitem.l_discount)), ' +sum ' ORDER BY nation.n_name) AS revenue, CONCAT('δ(', STRING_AGG(customer.prov || ' . ' || orders.prov || ' . ' || lineitem.prov || ' . ' || supplier.prov || ' . ' || nation.prov || ' . ' || region.prov, ' + ' ORDER BY nation.n_name), ')') AS prov FROM customer INNER JOIN orders ON customer.c_custkey = orders.o_custkey INNER JOIN lineitem ON lineitem.l_orderkey = orders.o_orderkey INNER JOIN supplier ON lineitem.l_suppkey = supplier.s_suppkey AND customer.c_nationkey = supplier.s_nationkey INNER JOIN nation ON supplier.s_nationkey = nation.n_nationkey INNER JOIN region ON nation.n_regionkey = region.r_regionkey WHERE region.r_name = 'EUROPE' AND orders.o_orderdate >= TO_DATE('1993-01-01', 'YYYY-MM-DD') AND orders.o_orderdate < TO_DATE('1994-01-01', 'YYYY-MM-DD') GROUP BY n_name ORDER BY revenue DESC

SELECT STRING_AGG(CONCAT('(',lineitem.prov, ')', ' ⊗ ', l_extendedprice * l_discount), ' +sum ') AS revenue, CONCAT('δ(',STRING_AGG(lineitem.prov, ' + '),')') AS prov FROM lineitem WHERE l_shipdate >= TO_DATE('1993-01-01', 'YYYY-MM-DD') AND l_shipdate < TO_DATE('1994-01-01', 'YYYY-MM-DD') AND l_discount >= 0.08 AND l_discount < 0.1 AND l_quantity < 24

SELECT supp_nation, cust_nation, l_year, STRING_AGG(CONCAT('(',shipping.prov  , ')', ' ⊗ ', volume), ' +sum ' ORDER BY supp_nation) AS revenue, CONCAT('δ(',STRING_AGG(shipping.prov  , ' + ' ORDER BY supp_nation),')') AS prov FROM (SELECT n1.n_name AS supp_nation, n2.n_name AS cust_nation, EXTRACT(year FROM lineitem.l_shipdate) AS l_year, lineitem.l_extendedprice * (1 - lineitem.l_discount) AS volume, supplier.prov || ' . ' || lineitem.prov || ' . ' || orders.prov || ' . ' || customer.prov || ' . ' || n1.prov || ' . ' || n2.prov AS prov FROM supplier INNER JOIN lineitem ON supplier.s_suppkey = lineitem.l_suppkey INNER JOIN orders ON orders.o_orderkey = lineitem.l_orderkey INNER JOIN customer ON customer.c_custkey = orders.o_custkey INNER JOIN nation n1 ON supplier.s_nationkey = n1.n_nationkey INNER JOIN nation n2 ON customer.c_nationkey = n2.n_nationkey WHERE ((n1.n_name = 'RUSSIA' AND n2.n_name = 'IRAN') OR (n1.n_name = 'IRAN' AND n2.n_name = 'RUSSIA')) AND lineitem.l_shipdate BETWEEN date '1995-01-01' AND date '1996-12-31') AS shipping GROUP BY supp_nation, cust_nation, l_year ORDER BY supp_nation, cust_nation, l_year;